version: "3.4"
services:
  db:
    image: postgres:14-bullseye
    container_name: tripscribe_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tripscribe
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9-alpine
    container_name: car-migo_flyway
    command: -url=jdbc:postgresql://db/carmigo -schemas=public -user=admin
      -password=password -connectRetries=5 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db