version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      PGUSER: admin
      POSTGRES_DB: tripscribe
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/tripscribe -schemas=public -user=admin
      -password=password -connectRetries=5 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
  server:
    profiles: ["dev"]
    build:
      context: ./server
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_URLS: "https://+:7121;http://+:5126"
      DbConnectionString: "Server=db,5432;Database=tripscribe;User Id=admin;Password=password;"
    volumes:
      - ./server:/app
    ports:
      - 7121:7121
      - 5126:5126
    depends_on:
      - flyway
volumes:
  db:
