FROM mcr.microsoft.com/dotnet/sdk:6.0

RUN apt-get update

WORKDIR /app

RUN dotnet dev-certs https --trust

ENV DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1

ENTRYPOINT ["sh", "-c"]

CMD ["dotnet restore && dotnet watch --project src/tripscribe.Api/tripscribe.Api.csproj"]