name: Verify Server

on:
  pull_request:
      branches: [ develop, main ]
      paths:
        - "database/**"
        - "server/**"

default:
  run:
    working-directory: ./server

jobs: 
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: Restore nuget
        run: dotnet restore && dotnet build
      - name: Test with dotnet
        run: |
          dotnet test --no-restore -c Release
          